"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = AccountPage;
var jsx_runtime_1 = require("react/jsx-runtime");
var react_router_dom_1 = require("react-router-dom");
var api_1 = require("../api");
var live_1 = require("../live");
var AccountPositions_1 = require("../components/AccountPositions");
var groups_1 = require("../groups");
function AccountPage() { var _a = (0, react_router_dom_1.useParams)().loginHint, loginHint = _a === void 0 ? "" : _a; var _b = useState(null), snapshot = _b[0], setSnapshot = _b[1]; var _c = useState([]), positions = _c[0], setPositions = _c[1]; var _d = useState(undefined), updatedAt = _d[0], setUpdatedAt = _d[1]; var _e = useState(null), error = _e[0], setError = _e[1]; var _f = useState((0, groups_1.getGroup)(loginHint)), group = _f[0], setGroupState = _f[1]; useEffect(function () { setError(null); (0, api_1.fetchAccountPositions)(loginHint).then(function (_a) {
    var snapshot = _a.snapshot, positions = _a.positions, updated_at = _a.updated_at;
    setSnapshot(snapshot);
    setPositions(positions || []);
    setUpdatedAt(updated_at);
}).catch(function (err) { return setError(err.message); }); var unsub = (0, live_1.subscribe)(function (evt) { if (evt.type !== "positions_snapshot")
    return; if (evt.account !== loginHint)
    return; setSnapshot(evt.snapshot); setPositions(Array.isArray(evt.positions) ? evt.positions : []); setUpdatedAt(evt.ts); }); setGroupState((0, groups_1.getGroup)(loginHint)); return function () { return unsub(); }; }, [loginHint]); var handleGroup = function (g) { (0, groups_1.setGroup)(loginHint, g); setGroupState(g); }; return ((0, jsx_runtime_1.jsxs)("div", { style: { display: "grid", gap: 16 }, children: ["      ", (0, jsx_runtime_1.jsxs)("div", { style: { display: "flex", alignItems: "center", gap: 12 }, children: ["        ", (0, jsx_runtime_1.jsx)(react_router_dom_1.Link, { to: "/", className: "muted", children: "\u2190 Back" }), "        ", (0, jsx_runtime_1.jsxs)("h2", { style: { fontSize: 20, fontWeight: 800, letterSpacing: ".02em", margin: 0 }, children: ["Account: ", loginHint] }), "        ", (0, jsx_runtime_1.jsxs)("div", { style: { marginLeft: "auto", display: "flex", alignItems: "center", gap: 8 }, children: ["          ", (0, jsx_runtime_1.jsx)("span", { className: "muted", style: { fontSize: 12 }, children: "Group:" }), "          ", (0, jsx_runtime_1.jsxs)("select", { value: group, onChange: function (e) { return handleGroup(e.target.value); }, style: { background: "#0e1422", color: "var(--text)", border: "1px solid var(--border)", borderRadius: 8, padding: "6px 8px" }, children: ["            ", (0, jsx_runtime_1.jsx)("option", { value: "All", children: "All" }), "            ", (0, jsx_runtime_1.jsx)("option", { value: "E2T", children: "E2T" }), "            ", (0, jsx_runtime_1.jsx)("option", { value: "Nish", children: "Nish Algos" }), "          "] }), "        "] }), "      "] }), "      ", error ? ((0, jsx_runtime_1.jsx)("div", { className: "rowcard", style: { borderColor: "rgba(239,68,68,.35)" }, children: error })) : ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: ["          ", (0, jsx_runtime_1.jsxs)("div", { style: { display: "flex", gap: 12, flexWrap: "wrap" }, children: ["            ", (0, jsx_runtime_1.jsx)(KPI, { label: "Balance", value: fmt(snapshot === null || snapshot === void 0 ? void 0 : snapshot.balance) }), "            ", (0, jsx_runtime_1.jsx)(KPI, { label: "Equity", value: fmt(snapshot === null || snapshot === void 0 ? void 0 : snapshot.equity) }), "            ", (0, jsx_runtime_1.jsx)(KPI, { label: "Margin", value: fmt(snapshot === null || snapshot === void 0 ? void 0 : snapshot.margin) }), "            ", (0, jsx_runtime_1.jsx)(KPI, { label: "Free", value: fmt(snapshot === null || snapshot === void 0 ? void 0 : snapshot.margin_free) }), "          "] }), "          ", (0, jsx_runtime_1.jsxs)("div", { className: "muted", style: { fontSize: 12 }, children: ["            Updated: ", updatedAt ? new Date(updatedAt).toLocaleTimeString() : "—", "          "] }), "          ", (0, jsx_runtime_1.jsx)(AccountPositions_1.default, { positions: positions }), "        "] })), "    "] })); }
function KPI(_a) {
    var label = _a.label, value = _a.value;
    return ((0, jsx_runtime_1.jsxs)("div", { className: "kpi", children: ["      ", (0, jsx_runtime_1.jsx)("div", { className: "label", children: label }), "      ", (0, jsx_runtime_1.jsx)("div", { className: "value", children: value }), "    "] }));
}
function fmt(n) { if (typeof n !== "number")
    return "—"; return n.toLocaleString(undefined, { maximumFractionDigits: 2 }); }
