"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = App;
var jsx_runtime_1 = require("react/jsx-runtime");
var react_router_dom_1 = require("react-router-dom");
var Overview_1 = require("./pages/Overview");
var AccountPage_1 = require("./pages/AccountPage");
var Tabs_1 = require("./components/Tabs");
function App() { return ((0, jsx_runtime_1.jsxs)("div", { style: { minHeight: "100vh" }, children: ["      ", (0, jsx_runtime_1.jsxs)("header", { className: "header", children: ["        ", (0, jsx_runtime_1.jsxs)("div", { className: "header-inner", children: ["          ", (0, jsx_runtime_1.jsx)("div", { style: { width: 10, height: 10, borderRadius: 999, background: "linear-gradient(135deg, var(--accent), var(--accent-2))", boxShadow: "0 0 16px rgba(124,58,237,0.6)" } }), "          ", (0, jsx_runtime_1.jsx)(react_router_dom_1.Link, { to: "/", children: (0, jsx_runtime_1.jsx)("h1", { style: { fontSize: 18, fontWeight: 800, letterSpacing: ".02em", margin: 0 }, children: "EAs Dashboard" }) }), "          ", (0, jsx_runtime_1.jsx)("div", { style: { marginLeft: "auto", fontSize: 13, color: "var(--muted)" }, children: "Dark \u00B7 Switzer" }), "        "] }), "      "] }), "      ", (0, jsx_runtime_1.jsxs)("main", { style: { padding: 20 }, children: ["        ", (0, jsx_runtime_1.jsxs)("div", { style: { maxWidth: 1200, margin: "0 auto" }, children: ["          ", (0, jsx_runtime_1.jsx)(Tabs_1.default, {}), "          ", (0, jsx_runtime_1.jsxs)(react_router_dom_1.Routes, { children: ["            ", (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/", element: (0, jsx_runtime_1.jsx)(Overview_1.default, { filter: "All" }) }), "            ", (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/all", element: (0, jsx_runtime_1.jsx)(Overview_1.default, { filter: "All" }) }), "            ", (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/e2t", element: (0, jsx_runtime_1.jsx)(Overview_1.default, { filter: "E2T" }) }), "            ", (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/nish", element: (0, jsx_runtime_1.jsx)(Overview_1.default, { filter: "Nish" }) }), "            ", (0, jsx_runtime_1.jsx)(react_router_dom_1.Route, { path: "/account/:loginHint", element: (0, jsx_runtime_1.jsx)(AccountPage_1.default, {}) }), "          "] }), "        "] }), "      "] }), "    "] })); }
